export const supabaseUrl = "https://pzssblashmuxspoybqig.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6c3NibGFzaG11eHNwb3licWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODMyODMsImV4cCI6MjA2Njk1OTI4M30.ghxpgNsOK1dGLaeZV1O2pub-SHZNGBJuiboFGVz23so";
